{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Features data set\",\"sales data-set\",\"stores data-set\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "affd107d-34c8-4249-b567-291526d8ad2e",
        "fromColumn": "Date",
        "fromTable": "Features data set",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e72ff02-eaa9-46c5-a04b-87c683ec3865"
      },
      {
        "name": "b8c819a4-6a0e-4185-8106-48e46dbf1fe9",
        "fromColumn": "Store",
        "fromTable": "Features data set",
        "toColumn": "Store",
        "toTable": "stores data-set"
      },
      {
        "name": "ccfacdf7-053b-4737-8f0c-d19a25ddf1e3",
        "fromColumn": "Store",
        "fromTable": "sales data-set",
        "toColumn": "Store",
        "toTable": "stores data-set"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Features data set",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd30e187-9303-4f83-9061-c605a51afe8c",
            "sourceColumn": "Store",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "670c8001-6e47-4d9c-996e-777a42f793fd",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9e72ff02-eaa9-46c5-a04b-87c683ec3865"
                },
                "isDefault": true,
                "relationship": "affd107d-34c8-4249-b567-291526d8ad2e"
              }
            ]
          },
          {
            "name": "Temperature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1fe469bb-deaf-442d-a4c9-284c9ced8dc6",
            "sourceColumn": "Temperature",
            "summarizeBy": "sum"
          },
          {
            "name": "Fuel_Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "31e18d0e-27f4-4b9e-a795-f714ccbf5563",
            "sourceColumn": "Fuel_Price",
            "summarizeBy": "sum"
          },
          {
            "name": "MarkDown1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71718917-8e66-48d6-9c31-26685ab280df",
            "sourceColumn": "MarkDown1",
            "summarizeBy": "none"
          },
          {
            "name": "MarkDown2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5e3d4eb-2de9-4486-b710-72655bbed796",
            "sourceColumn": "MarkDown2",
            "summarizeBy": "none"
          },
          {
            "name": "MarkDown3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fae80a26-d2cc-4ba3-9042-cd474bdfe732",
            "sourceColumn": "MarkDown3",
            "summarizeBy": "none"
          },
          {
            "name": "MarkDown4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1eb3075a-84aa-47b4-9548-153aa0b87efb",
            "sourceColumn": "MarkDown4",
            "summarizeBy": "none"
          },
          {
            "name": "MarkDown5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2617a00c-3c2c-49e0-ba36-ac225aaf925d",
            "sourceColumn": "MarkDown5",
            "summarizeBy": "none"
          },
          {
            "name": "CPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c8fae00-17c0-4a0e-ac7a-43e7b26a54c7",
            "sourceColumn": "CPI",
            "summarizeBy": "none"
          },
          {
            "name": "Unemployment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf07d66d-a630-4319-a6c2-63c1c15b496e",
            "sourceColumn": "Unemployment",
            "summarizeBy": "none"
          },
          {
            "name": "IsHoliday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9e7b186d-734e-45ad-a150-ae3fc8a5fb6f",
            "sourceColumn": "IsHoliday",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2740f996-4e87-4c17-b0e6-d4ba5be42ff6",
        "partitions": [
          {
            "name": "Features data set",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\neo2g\\OneDrive\\Documentos\\Github Repos\\Power-BI-portifolio\\Databases\\DB - Retail Data Analytics\\Features data set.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Store\", Int64.Type}, {\"Date\", type text}, {\"Temperature\", type number}, {\"Fuel_Price\", type number}, {\"MarkDown1\", type text}, {\"MarkDown2\", type text}, {\"MarkDown3\", type text}, {\"MarkDown4\", type text}, {\"MarkDown5\", type text}, {\"CPI\", type text}, {\"Unemployment\", type text}, {\"IsHoliday\", type logical}}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Changed Type\", {{\"Date\", type date}}, \"pt-BR\")",
                "in",
                "    #\"Changed Type with Locale\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_33a4fb9b-c93e-4df5-9d98-6ce3f3b03938",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "704ec526-01de-41d9-bc51-b5802c304696",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f08d386c-3e7e-4393-973d-dce852bc99d3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a64823e3-6955-4278-902c-e41cc029d1c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "691a5e85-3186-4167-b2ce-17875887e467",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "db9b0246-9d91-427a-a466-eba4de9ebe67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "44bb008f-236f-470b-8c2e-292d657f3f3f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7878cf20-cf1d-4475-bddf-a65039f26913",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "36419a6e-83ef-4e0b-9c0a-291d0454b083",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a20cb12a-f3d1-425d-bd73-71166a2b289b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0f5093cf-e591-4b15-b9c6-acbc2b2ba63e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "88d6e775-5851-4813-aefc-442c09c4e127",
                "ordinal": 3
              }
            ],
            "lineageTag": "ac465ae0-0553-467d-a5a6-d41c4168d88b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9ece82c9-6262-43d3-9f51-e6bedb5715ec",
        "partitions": [
          {
            "name": "DateTableTemplate_33a4fb9b-c93e-4df5-9d98-6ce3f3b03938",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9e72ff02-eaa9-46c5-a04b-87c683ec3865",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "44318191-447f-40e9-8b6c-7ba8ea8ff500",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3d2339f4-8999-4fe2-ae34-f70b82114e90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1b1ef32c-2dad-4454-b5f6-d98bb84760b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4c96010f-daba-456d-8d10-27f797d6fc64",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ea9c656-cc6c-4bbf-b42d-4521bb176762",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "18489475-917f-432e-8c2d-a45b86495a0c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "363d2253-e00c-4117-a6ae-57bd1e507a29",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2cdca1c1-f831-4125-b274-c766998b49f2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5d57753a-6897-4b20-8fe2-36ee5b00a4b4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bf1dcf4e-0d4b-4d92-9c34-7820f12f913a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e2d556a3-2614-440b-8c60-e750779f6601",
                "ordinal": 3
              }
            ],
            "lineageTag": "5812db25-7241-46f0-bd23-19f6d02ac46c"
          }
        ],
        "isHidden": true,
        "lineageTag": "e79bc946-8b79-49a3-b461-2cce5f333dbb",
        "partitions": [
          {
            "name": "LocalDateTable_9e72ff02-eaa9-46c5-a04b-87c683ec3865",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Features data set'[Date])), 1, 1), Date(Year(MAX('Features data set'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "sales data-set",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa018ee8-01d6-4d14-ba09-e8479b3a889f",
            "sourceColumn": "Store",
            "summarizeBy": "none"
          },
          {
            "name": "Dept",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d11904cd-7b9a-4956-beb5-ec5090f13ae9",
            "sourceColumn": "Dept",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa12a8b8-b818-4e4b-8193-58b8ad7c28cc",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Weekly_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a62d790-7b85-4665-a012-d7686e9bf5bc",
            "sourceColumn": "Weekly_Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "IsHoliday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "68363b49-5783-4231-bf91-4aeaf432ca56",
            "sourceColumn": "IsHoliday",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "933edb02-b532-45c0-ac22-793e7779a94a",
        "partitions": [
          {
            "name": "sales data-set",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\neo2g\\OneDrive\\Documentos\\Github Repos\\Power-BI-portifolio\\Databases\\DB - Retail Data Analytics\\sales data-set.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Store\", Int64.Type}, {\"Dept\", Int64.Type}, {\"Date\", type text}, {\"Weekly_Sales\", type number}, {\"IsHoliday\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "stores data-set",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a17d19af-ef64-4791-a1e6-48a2435bd3a7",
            "sourceColumn": "Store",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76aabdfc-b2f3-4c06-b3a8-6dd53fe70649",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80549667-8abc-475d-a79d-078c63c69645",
            "sourceColumn": "Size",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0d25ff07-4517-4b90-ae85-5766e57cc5de",
        "partitions": [
          {
            "name": "stores data-set",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\neo2g\\OneDrive\\Documentos\\Github Repos\\Power-BI-portifolio\\Databases\\DB - Retail Data Analytics\\stores data-set.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Store\", Int64.Type}, {\"Type\", type text}, {\"Size\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}